name: pot_g
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  slang: ^4.6.0
  slang_flutter: ^4.6.0
  flutter_svg: ^2.0.17
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  auto_route: ^10.0.1
  amplitude_flutter: ^4.3.0
  flutter_localizations:
    sdk: flutter
  dynamic_fonts: ^2.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  auto_route_generator: ^10.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true
